#!/bin/sh

while :
do
read CH
{
case "$CH" in
"1")
echo 77 > /sys/class/gpio/export
echo out > /sys/class/gpio/PC13/direction
echo 0 > /sys/class/gpio/PC13/value
echo "*** LED1 ON ****"

;;

"2")
echo 81 > /sys/class/gpio/export
echo out > /sys/class/gpio/PC17/direction
echo 0 > /sys/class/gpio/PC17/value
echo "*** LED2 ON ****"
;;

"3")                                     
echo 83 > /sys/class/gpio/export         
echo out > /sys/class/gpio/PC19/direction
echo 0 > /sys/class/gpio/PC19/value      
echo "*** LED3 ON ****"                  
;;                                       
 "4")    
echo "********************************"
echo
echo "----------- RTC TEST -----------"
echo
echo "********************************"
echo

if [ -e "/dev/rtc0" ]
then
    echo "RTC device found: /dev/rtc0"
else
    echo "No RTC device found"
fi

echo
echo "Restarting chronyd service..."
#systemctl restart chronyd
echo                                   
echo "Setting timezone to Asia/Calcutta..."
ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
                                                      
echo                                                  
echo "Current date and time:"                         
date                                                  
                                                      
echo                                                  
var=$(date)                                           
if [ "$var" == "$var" ]                               
then                                                  
    echo "********* PASS **************"              
else                                                  
    echo "********* FAIL **************"              
fi   
;;
"5")
echo "*********************************"
echo
echo "---------- TEST ADC  -----------"
echo
echo "*********************************"
#if [ -e "/sys/bus/iio/devices/iio\:device0/in_voltage6_raw " ]
#then
   echo "ADC NODE EXISTS"

 var=$( cat /sys/bus/iio/devices/iio\:device0/in_voltage6_raw )

    echo "======= PERFORMING ADC TEST ===="
    echo $var
    echo
    echo "========= PASS ================"
    echo
#else
#    echo " ADC NODE NOT  FOUND"
#    echo "========== FAIL ============="
#fi
;;
"6")
echo "******************************************"
echo
echo "---------- TEST Ethernet -----------------"
echo
echo "*******************************************"

if udhcpc -i eth0 ;
 then
    echo
    echo "============= PASS =============="
    echo
    echo "eth0 interface configured successfully"
    echo "carrier status:"
    cat /sys/class/net/eth0/carrier
    echo "========= press ctrl+c to stop pinging ========"

    ping google.com

else
    echo "Failed to configure eth0 interface"
    echo "============= FAIL =============="
fi 

;;
"7")
echo "************************************"
echo
echo "---------BUTTON/SWITCH TEST--------"
echo
echo "***********************************"
echo

# Export GPIO pin 76
echo 76 > /sys/class/gpio/export

echo "Status of Button: "

# Read the value of the GPIO pin
status=$(cat /sys/class/gpio/PC12/value)

if [ "$status" -eq 0 ]; then
    echo "Button released"
    echo
    echo "******** PASS *********"
    echo
else
 echo "Button pressed"         
    echo                          
    echo "******** FAIL *********"
    echo                          
fi     
;;
"8")
echo "*************************************"
echo
echo "------------- PWM Test---------------"
echo
echo "*************************************"
if [ -d "/sys/class/pwm/pwmchip0/" ]
then
    echo "PWM Exist"
    echo
    echo 0 > /sys/class/pwm/pwmchip0/export
    echo "PWM Test"
    echo
    sleep 3
    echo "Setting PWM Time Period"
    echo 50000 > /sys/class/pwm/pwmchip0/pwm0/period
    echo
    echo "Setting duty cycle"
    echo 2500 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
    echo
    sleep 3
    echo 1200 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
    echo "Enabling PWM"
 echo 0 > /sys/class/pwm/pwmchip0/pwm0/enable       
#    cat /sys/kernel/debug/pwm                         
    echo                                               
    echo 1 > /sys/class/pwm/pwmchip0/pwm0/enable       
    sleep 3                                            
    echo                                               
    status=$(cat /sys/class/pwm/pwmchip0/pwm0/enable)
    if [ "$status" == "1" ]                          
    then                                             
        echo                                         
        echo "============= PASS ==============="    
        echo                                           
    else                                               
        echo                                           
        echo "============= FAIL ==============="      
        echo                                           
    fi                                                 
else                                                   
    echo "No PWM chip found"                           
    echo "============= FAIL ==============="          
fi                                                     
;;
"9")
echo  "******************************"
echo
echo "------ TEST USART  ------------"
echo
echo  "******************************"
if [ -e "/dev/ttyS1" ]
then
echo "ADC NODE EXIST"
echo
echo "------------ performing UART Test ------- "
echo
echo "--------------------- PASS ----------------"
echo
else
echo "USART Node NOT Found "
echo "--------------------- FAIL ----------------"
fi
;;
"10")
echo "*********************************"
echo
echo "---------- TEST ADC  -----------"
echo
echo "*********************************"
#if [ -e "/sys/bus/iio/devices/iio\:device0/in_voltage6_raw " ]
#then
   echo "ADC NODE EXISTS"

 var=$( cat /sys/bus/iio/devices/iio\:device0/in_voltage6_raw )

    echo "======= PERFORMING ADC TEST ===="
    echo $var
    echo
    echo "========= PASS ================"
    echo
#else
#    echo " ADC NODE NOT  FOUND"
#    echo "========== FAIL ============="
#fi
"11")
echo "***************************************************"
echo
echo "----------------- RS485 TEST ---------------------"
echo
echo "***************************************************"
echo
echo "-----checking for RS485----"
echo

if [ -e "/dev/ttyS2" ]
then
    echo " RS485 Node exists"
    echo
    echo " ------ Performing 485-----"
    echo
    echo "************* PASS **************"
    echo " press Ctrl+C to exit to microcom "
    microcom -s 115200 /dev/ttyS2

else
    echo "------ FAIL ------"
    echo "RS485 Node not found"
fi
"12")
echo "***************************************************"
echo
echo "=============== TEST SD CARD ======================"
echo
echo "***************************************************"
touch /data/Testing/data.txt
echo " Welcome on phytec " > data.txt

if [ -e "/dev/mmcblk1p2" ]
then
  echo "SD card found on the board"
  echo "---------mounting the sd card--------"
  mount /dev/mmcblk1p2 /mnt/
  cd /mnt/
  echo "copying file from board to sd card"
  cp /data/Testing/data.txt /mnt/
  if [ -e "/mnt/data.txt" ]
 then
    echo "copying of file from board to sd card successful"
    echo "*************PASS**********"
fi
"13")
 echo " ***************** "                   
echo                                                                           
echo " ------------------------ TEST USB ------------------------------------ "
echo                                                        
echo " ***************** "
echo                                                 
echo " Insert any pen drive to board for USB Test "
echo                                              
echo " Waiting for 5 sec "                        
sleep 5                                                          
echo " Creating test file "                                      
touch /data/Testing/file.txt                                     
echo " Welcome on phytec " > file.txt                            
                                                                 
if [ -e "/dev/sda" ] || [ -e "/dev/sdb" ] || [ -e "/dev/sdc" ]   
then                                                             
    echo                                                         
    echo " USB device plugged in to board "          
    echo " ------- Mounting the USB device -------- "

    echo                                                                       
    mount /dev/sda /mnt                                                        
    cd /mnt || exit                                                            
    echo " Copying file from board to USB device "                             
    echo                                                    
    cp /data/Testing/file.txt /mnt                          
    cd / || exit                                   
                                                   
    if [ -e "/mnt/file.txt" ]                     
    then                             
        echo " Copying file from board to USB device successful "
        echo                                                     
        echo "============= PASS ==============="                
        echo                                                     
    else                                                         
        echo " Files not copied "                                
        echo "============= FAIL ==============="    
    fi                                               
else                                                 
    echo " USB device not found "                    
    echo "============= FAIL ==============="     
fi

"14")
echo  "***************************************************"
echo
echo "------------------- DOUT TEST ----------------------"
echo
echo  "***************************************************"
echo "check if R63 resiter mounted or not "
echo
echo "------------ GPIOPIN-5 --------------"
echo
echo 17 > /sys/class/gpio/export
echo
if [ -d "/sys/class/gpio/PA17" ]
then
    echo "GPIO Exported"
else
    echo "GPIO Exported Failed"
fi
echo out > /sys/class/gpio/PA17/direction
echo 1 > /sys/class/gpio/PA17/value
sleep 2
echo 0 > /sys/class/gpio/PA17/value
sleep 2
gpio_value=$(cat /sys/class/gpio/PA17/value)
if [ "$gpio_value" == 1 ]
then
    echo " DOUT CONNECTED "
    echo
    echo "============= PASS ==============="
    echo
else
    echo " DOUT NOT CONNECTED "
    echo
    echo "============= FAIL==============="
    echo
fi
esac                                                  
}                                           
done  

