/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//#include <stdint.h>

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
 // #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif

//int main(void)
//{
 //   /* Loop forever */
	//for(;;);
//}
//
#include"stm32f411x.h"
void delay(int T)
{
	int i;
	for(i=0;i<5000;i++);
}
int main()
{
	int T;
	RCC->AHB1ENR |=1;
	GPIOA->MODER |=0X400;
	while(T--)
	{
		GPIOA->ODR=0X20;
		delay(500);
		GPIOA->ODR=0X20;
		delay(500);

	}
}
